server:
  port: 8090

management:
  security:
    enabled: false    

promotion: action

spring:
  application:
    name: awesome-media-backend
  datasource:
    initialize: true
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mediadb;
    username: sa
    password: null
  h2:
    console:
      enabled: true      

logging:
  path: ../log/${spring.application.name}      
